language: node_js
sudo: false
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
before_install:
  - "npm install -g bower"
  - "npm install -g browserify"
  - "npm install -g dereserve"
  - "npm install -g derequire"
  - "npm install -g mocha"
  - "npm install -g mocha-phantomjs"
before_script:
  - "npm run bower"
script:
  - "npm test"
